<a href="https://colab.research.google.com/github/ANAGHA-SREYAS/python_practice/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Write a Numpy program to get the Numpy version.

In [2]:
import numpy as np
print(np.__version__)


1.25.2
<function show at 0x7b0b5b3f88b0>


2. Write a NumPy program to get help with the add function

In [3]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
sum=np.add(arr1,arr2)
sum

array([ 6,  8, 10, 12])

3. Write a NumPy program to test whether none of the elements of a given array are zero.

In [8]:
import numpy as np
def non_zero(arr):
  return np.all(arr!=0)

arr1=np.array([1,2,3,4])
arr2=np.array([5,6,0,8])
print(non_zero(arr1))
print(non_zero(arr2))

True
False


4. Write a NumPy program to test if any of the elements of a given array are non-zero.

In [13]:
import numpy as np
def non_zero(arr):
  return np.any(arr!=0)
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,0,8])
print(non_zero(arr1))
print(non_zero(arr2))

True
True


5. How to create a 1D array?

In [16]:
import numpy as np
x=[1,2,3,4,5]
arr=np.array(x)
print(arr)
print('the dimension is',arr.ndim)

[1 2 3 4 5]
the dimension is 1


6.How to create a boolean array?

# Question : Create a 3×3 numpy array of all True’s

In [17]:
import numpy as np
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

How to extract items that satisfy a given condition from 1D array?
Question : Extract all odd numbers from array
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([1, 3, 5, 7, 9])

In [18]:
import numpy as np
arr=np.arange(0,10)
new_arr=arr[arr%2!=0]
new_arr

array([1, 3, 5, 7, 9])

 How to replace items that satisfy a condition with another value in numpy array?
 Question: Replace all odd numbers in arr with -1
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [19]:
import numpy as np
arr=np.arange(10)
arr[arr%2!=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

How to replace items that satisfy a condition without affecting the original array?
Question: Replace all odd numbers in arr with -1 without changing arr
# input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# output: out
# array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
# arr
# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
import numpy as np
arr=np.arange(10)
new_arr=arr.copy()
new_arr[new_arr%2!=0]=-1
print("the original array",arr)
print('the modified array',new_arr)

the original array [0 1 2 3 4 5 6 7 8 9]
the modified array [ 0 -1  2 -1  4 -1  6 -1  8 -1]


How to reshape an array?
Question: Convert a 1D array to a 2D array with 2 rows
# input: np.arange(10)
# output array([[0, 1, 2, 3, 4],
#               [5, 6, 7, 8, 9]])

In [27]:
import numpy as np
arr=np.arange(10)
arr.reshape(2,5)



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

 How to stack two arrays vertically?
 Question: Stack arrays a and b vertically
# input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)

# output: array([[0, 1, 2, 3, 4],
#                [5, 6, 7, 8, 9],
#                [1, 1, 1, 1, 1],
#                [1, 1, 1, 1, 1]])

In [32]:
import numpy as np
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

How to stack two arrays horizontally?

Question: Stack the arrays a and b horizontally.

# Input: a = np.arange(10).reshape(2,-1)
#        b = np.repeat(1, 10).reshape(2,-1)
# Output: array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#                [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [33]:
import numpy as np
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

How to generate custom sequences in numpy without hardcoding?


Question: Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])


In [37]:
import numpy as np
a = np.array([1,2,3])
repeated_a=np.tile(a,3)
final_output=np.tile(repeated_a,len(a))
final_output

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1,
       2, 3, 1, 2, 3])

 How to get the common items between two python numpy arrays?
 Question: Get the common items between a and b

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: array([2, 4])

In [39]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])


common_elements = a[np.isin(a, b)]
common_elements = np.unique(common_elements)
common_elements


array([2, 4])

How to remove from one array those items that exist in another?

From array a remove all items present in array b

# Input: a = np.array([1,2,3,4,5])
#        b = np.array([5,6,7,8,9])

# Output: array([1,2,3,4])

In [44]:
import numpy as np
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
arr=np.array([x for x in a if x not in b])
arr

array([1, 2, 3, 4])

 How to get the positions where elements of two arrays match?
 Question: Get the positions where elements of a and b match

# Input: a = np.array([1,2,3,2,3,4,3,4,5,6])
#        b = np.array([7,2,10,2,7,4,9,4,9,8])

# Output: (array([1, 3, 5, 7]),)

In [46]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
x=np.where(a==b)
print(x)

(array([1, 3, 5, 7]),)


 Question: Get all items between 5 and 10 from a.

# Input: a = np.array([2, 6, 1, 9, 10, 3, 27])
# Output: (array([6, 9, 10]),)


In [54]:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
arr=a[(a<=10) & (a>5)]
arr

array([ 6,  9, 10])

Question: Swap columns 1 and 2 in the array arr.

# Input:

arr = np.arange(9).reshape(3,3)

print('Original array')

arr

In [58]:
import numpy as np
arr = np.arange(9).reshape(3,3)
print('original array\n',arr)
arr[:,[1,2]]=arr[:,[2,1]]
print('array after swaping\n',arr)


original array
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
array after swaping
 [[0 2 1]
 [3 5 4]
 [6 8 7]]


Question: Swap rows 1 and 2 in the array arr:

# Input:

arr = np.arange(9).reshape(3,3)

print('Original array')

arr

In [61]:
import numpy as np
arr = np.arange(9).reshape(3,3)
print('original array\n',arr)
arr[[1,2]]=arr[[2,1]]
print('array after swaping\n',arr)



original array
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
array after swaping
 [[0 1 2]
 [6 7 8]
 [3 4 5]]


Question: Reverse the rows of a 2D array arr.

# Input:

arr = np.arange(9).reshape(3,3)

print('Original array')

arr

In [64]:
import numpy as np
arr = np.arange(9).reshape(3,3)
print('original array\n',arr)
arr[:]=arr[::-1]
print('the reversed array\n',arr)

original array
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
the reversed array
 [[6 7 8]
 [3 4 5]
 [0 1 2]]


Question: Reverse the columns of a 2D array arr.

# Input: arr = np.arange(9).reshape(3,3)

In [66]:
import numpy as np
arr = np.arange(9).reshape(3,3)
print('original array\n',arr)
arr[:]=arr[:,::-1]
print('the reversed array\n',arr)

original array
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
the reversed array
 [[2 1 0]
 [5 4 3]
 [8 7 6]]


Question: Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.


In [67]:
import numpy as np
np.random.uniform(5,10,size=(5,3))

array([[7.96281005, 5.27843343, 8.14701389],
       [7.90393469, 5.5005074 , 5.19761721],
       [7.48188333, 8.67795681, 8.39985916],
       [8.5234053 , 7.1623754 , 6.15137583],
       [9.34769191, 9.92934969, 9.02446589]])

Question: Print or show only 3 decimal places of the numpy array rand_arr.


In [71]:
import numpy as np
arr=np.random.rand(5,3)
np.set_printoptions(precision=3)
print(arr)

[[0.874 0.976 0.264]
 [0.584 0.12  0.268]
 [0.014 0.392 0.183]
 [0.868 0.563 0.504]
 [0.889 0.742 0.703]]
